"""Builds client_autorun.txt: iris_theme.luau and iris_viewer.luau in one piece to
paste into the console's Client Autorun tab.

Pasted code is one chunk, and Deadline's Fiu VM cannot load a function spanning
more than 255 lines (see tools/check_fiu_compat.py), so the two files cannot just
be joined. Instead each becomes a function passed to one call, `return run(theme,
viewer)`. The compiler puts that call and its return on the line the call starts,
and adds no implicit return at the end of a chunk that ends with `return`, so the
top level only reaches the line where the viewer's function starts; each file
keeps its own 255-line budget. (A plain call as the last statement is not enough:
the implicit return lands on the file's last line.)

Usage:
    python tools/build_client_autorun.py           # write client_autorun.txt
    python tools/build_client_autorun.py --check   # exit 1 if it is out of date
"""
import sys

import deadline_data as dd

OUTPUT = dd.ROOT / "client_autorun.txt"
PARTS = [("theme", dd.ROOT / "iris_theme.luau"), ("viewer", dd.ROOT / "iris_viewer.luau")]

HEADER = """\
-- Deadline stat printer: Iris viewer + theme, for the console's Client Autorun tab.
-- Copy this whole file into Client Autorun. Settings are at the top of each part below:
-- the theme (fonts, colors) first, then the viewer (ONLY_FOR, page size). Guide: IRIS_VIEWER.md
-- GENERATED by tools/build_client_autorun.py from iris_theme.luau and iris_viewer.luau.
local function run(...) for _, part in ipairs({ ... }) do part() end end
"""


def build():
    bodies = [path.read_text(encoding="utf-8").rstrip("\n") for _, path in PARTS]
    parts = ",\n".join(f"function() -- {name}\n{body}\nend" for (name, _), body in zip(PARTS, bodies))
    return HEADER + f"return run({parts})\n"


def main(argv):
    text = build()
    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.name} is out of date: run python tools/build_client_autorun.py")
            return 1
        print(f"{OUTPUT.name} is up to date.")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.name} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
